### PR TITLE
Cleaned up redundant matching

### PR DESCRIPTION
**Pull request by tomleb**

### CODE REVIEW

**Comment by tomleb** [comment]
I'm not sure the ? operator is in stable yet, I'll have to look that up and revert it back to try!. You decide.

**Comment by Cyberunner23** [comment]
Lets revert to try! for now, I was planning on making this work on stable rust once proc_macro is stabilized which seems like it will be before \`?\` operator gets stabilized.

For reference:
* https://github.com/rust-lang/rust/issues/31436
* https://github.com/rust-lang/rust/issues/35900

**Comment by dtolnay** [comment]
The ? operator has been stable since Rust 1.13 back in November. [See the announcement here](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html#the--operator). The issue you linked to is something different - allowing ? to apply to types other than Result.

**Comment by Cyberunner23** [comment]
Thanks for the clarification!

**Pull request merged**
